on:
  pull_request:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: gem update --system 3.2.3
      - run: mkdir -p certificates/
      - name: Decrypt PEM file
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output certificates/doconomy.pem doconomy.pem.gpg
      - run: bundle exec rspec spec/
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ruby_${{ matrix.ruby }}
          parallel: true
  finish:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
